veygo-app/main/default/objects/Customer_Support__c/Customer_Support__c.object-meta.xml
<CustomObject>
    <label>Customer Support</label>
    <nameField>
        <label>Customer Support Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Supports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

veygo-app/main/default/objects/Customer_Support__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Supports</relationshipLabel>
    <relationshipName>Customer_Supports</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

veygo-app/main/default/objects/Customer_Support__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Customer support category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Accessibility</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Life Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

veygo-app/main/default/objects/Customer_Support__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Customer support details</label>
    <type>TextArea</type>
</CustomField>

veygo-app/main/default/objects/Customer_Support__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Customer Email Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

veygo-app/main/default/objects/Customer_Support__c/fields/End_date__c.field-meta.xml
<CustomField>
    <fullName>End_date__c</fullName>
    <label>End date</label>
    <type>Date</type>
</CustomField>

veygo-app/main/default/objects/Customer_Support__c/fields/Scripting_complete__c.field-meta.xml
<CustomField>
    <fullName>Scripting_complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Scripting complete</label>
    <type>Checkbox</type>
</CustomField>

veygo-app/main/default/objects/Customer_Support__c/fields/Start_date__c.field-meta.xml
<CustomField>
    <fullName>Start_date__c</fullName>
    <label>Start date</label>
    <type>Date</type>
</CustomField>

veygo-app/main/default/objects/Customer_Support__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Customer support type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

veygo-app/main/default/classes/CustomerSupportService.cls
public with sharing class CustomerSupportService {
    private static rflib_Logger logger = rflib_LoggerUtil.getFactory().createLogger('CustomerSupportService');
    
    @AuraEnabled
	public static String createCustomerSupport(String customerSupportInfo){
		CustomerSupportInfo input = (CustomerSupportInfo)JSON.deserialize(customerSupportInfo, CustomerSupportInfo.class);
		Customer_Support__c customerSupport = new Customer_Support__c();
		customerSupport.AccountId__c = input.accountId;
		customerSupport.Email_Address__c = input.emailAddress;
		customerSupport.Category__c = input.category;
		customerSupport.Type__c = input.type != null ? input.type : '';
		customerSupport.Start_date__c = input.startDate;
		customerSupport.End_date__c = input.endDate;
		customerSupport.Details__c = input.details != null ? input.details : '';
		customerSupport.Scripting_complete__c = input.scriptingComplete;
		insert customerSupport;        
        return customerSupport.Id;
	}

    @AuraEnabled
	public static String updateCustomerSupport(String recordId, String customerSupportInfo){
		Customer_Support__c customerSupport = CustomerSupportSelector.getCustomerSupportById(recordId);

        CustomerSupportInfo input = (CustomerSupportInfo)JSON.deserialize(customerSupportInfo, CustomerSupportInfo.class);
		customerSupport.AccountId__c = input.accountId;
		customerSupport.Email_Address__c = input.emailAddress;
		customerSupport.Category__c = input.category;
		customerSupport.Type__c = input.type != null ? input.type : '';
		customerSupport.Start_date__c = input.startDate;
		customerSupport.End_date__c = input.endDate;
		customerSupport.Details__c = input.details != null ? input.details : '';
		customerSupport.Scripting_complete__c = input.scriptingComplete;
		update customerSupport;        
        return customerSupport.Id;
	}

    @TestVisible
    private class CustomerSupportInfo {
        @AuraEnabled
        public String accountId;
        @AuraEnabled
        public String emailAddress;
        @AuraEnabled
        public String category;      
        @AuraEnabled
        public String type;    
        @AuraEnabled
        public Date startDate;    
        @AuraEnabled
        public Date endDate;    
        @AuraEnabled
        public String details;    
        @AuraEnabled
        public Boolean scriptingComplete;
    }
}