veygo-app/main/default/objects/Customer_Support__c/Customer_Support__c.object-meta.xml
<CustomObject>
    <label>Customer Support</label>
    <nameField>
        <label>Customer Support Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Supports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

veygo-app/main/default/objects/Customer_Support__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Supports</relationshipLabel>
    <relationshipName>Customer_Supports</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

veygo-app/main/default/objects/Customer_Support__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Customer support category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Accessibility</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Life Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

veygo-app/main/default/objects/Customer_Support__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Customer support details</label>
    <type>TextArea</type>
</CustomField>

veygo-app/main/default/objects/Customer_Support__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Customer Email Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

veygo-app/main/default/objects/Customer_Support__c/fields/End_date__c.field-meta.xml
<CustomField>
    <fullName>End_date__c</fullName>
    <label>End date</label>
    <type>Date</type>
</CustomField>

veygo-app/main/default/objects/Customer_Support__c/fields/Scripting_complete__c.field-meta.xml
<CustomField>
    <fullName>Scripting_complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Scripting complete</label>
    <type>Checkbox</type>
</CustomField>

veygo-app/main/default/objects/Customer_Support__c/fields/Start_date__c.field-meta.xml
<CustomField>
    <fullName>Start_date__c</fullName>
    <label>Start date</label>
    <type>Date</type>
</CustomField>

veygo-app/main/default/objects/Customer_Support__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Customer support type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

veygo-app/main/default/classes/CustomerSupportSelector.cls
public with sharing class CustomerSupportSelector {
    private static rflib_Logger logger = rflib_LoggerUtil.getFactory().createLogger('CustomerSupportSelector');

    @AuraEnabled
    public static List<Customer_Support__c> getCustomerSupportByAccountId(String accountId){
		List<Customer_Support__c> customerSupportList = new List<Customer_Support__c>();
		if( Schema.Customer_Support__c.SObjectType.getDescribe().isAccessible() ){
			for(Customer_Support__c cs : [SELECT Id, Email_Address__c, Category__c, Type__c, Start_date__c, End_date__c, Details__c, Scripting_complete__c
								FROM Customer_Support__c 
								WHERE AccountId__c = :accountId
                                ORDER BY Start_date__c DESC
							]){
                customerSupportList.add(cs);
			}
		}else{
			logger.error('getCustomerSupportByAccountId(): User (userid: {0}) has no access right to Customer_Support__c', new List<Object> {String.valueOf(UserInfo.getUserId())});
		}		
		return customerSupportList;
	}

    public static Customer_Support__c getCustomerSupportById(String Id){
		Customer_Support__c customerSupport = null;
		if( Schema.Customer_Support__c.SObjectType.getDescribe().isAccessible() ){
			for(Customer_Support__c cs : [SELECT Id, Email_Address__c, Category__c, Type__c, Start_date__c, End_date__c, Details__c, Scripting_complete__c
								FROM Customer_Support__c 
								WHERE Id = :Id
							]){
                customerSupport = cs;
			}
		}else{
			logger.error('getCustomerSupportById(): User (userid: {0}) has no access right to Customer_Support__c', new List<Object> {String.valueOf(UserInfo.getUserId())});
		}		
		return customerSupport;
	}
}