veygo-app/main/default/objects/Account/fields/CognitoId__c.field-meta.xml
<CustomField>
    <fullName>CognitoId__c</fullName>
    <label>Cognito Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

veygo-app/main/default/objects/InsurancePolicy/fields/Policy_Number_Id__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Policy Number Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

veygo-app/main/default/objects/Lead/fields/Quote_Number__c.field-meta.xml
<CustomField>
    <fullName>Quote_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Quote Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

veygo-app/main/default/objects/Opportunity/fields/Quote_Number__c.field-meta.xml
<CustomField>
    <fullName>Quote_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Quote Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

veygo-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

veygo-app/test/default/classes/TestDataFactory.cls
/**
 * @description       : 
 * @author            : matteo.iacucci@emea.merkleinc.com
 * @group             : 
 * @last modified on  : 2021-08-06
 * @last modified by  : matteo.iacucci@emea.merkleinc.com
**/
@IsTest
public class TestDataFactory {

	private SObject obj;

	public TestDataFactory(SObject obj){
		this.obj = obj;
	}

	public SObject insertObj(){
		insert this.obj;
		return this.obj;
	}

	public SObject getObj(){
		return this.obj;
	}

	/**
	* @description create a person account with the indicated lastName, Email = <lastName>@test.com, cognitoId = Cognito_<lastName>
	* @author matteo.iacucci@emea.merkleinc.com | 2021-08-03 
	* @param lastName 
	* @return TestDataFactory 
	**/
	public static TestDataFactory createPersonAccount(String lastName){
		Id personAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
		Account a = new Account(
			RecordTypeId = personAccountRecordTypeId,
			LastName = lastName,
			PersonEmail = lastName + '@test.com',
			CognitoId__c = 'Cognito_' + lastName
		);

		return new TestDataFactory((SObject) a);
	}

	public static TestDataFactory createLead(String lastName){
		Lead l = new Lead(
			LastName = lastName,
			Email = lastName + '@test.com',
			Quote_Number__c = 'QN-' + lastName
		);

		return new TestDataFactory((SObject) l);
	}

	public static TestDataFactory createOpportunity(String quoteNumber, Id accountId ){
		Opportunity oppty = new Opportunity(
			AccountId = accountId,
			Name = quoteNumber,
			CloseDate = Date.today(),
			Quote_Number__c = quoteNumber,
			StageName = Constants.QUOTE_STARTED
		);
		return new TestDataFactory((SObject) oppty);
	}

	public static TestDataFactory createPolicy(String policyNumber, Id accountId){
		InsurancePolicy p = new InsurancePolicy(
			NameInsuredId = accountId,
			Name = policyNumber,
			PolicyName = policyNumber,
			Policy_Number_Id__c = policyNumber

		);
		return new TestDataFactory((SObject) p);
	}
	
}